# Generated by Django 4.1.1 on 2024-05-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0003_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ui.role'),
        ),
    ]
