# Generated by Django 4.1.1 on 2024-05-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0004_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='playable',
            field=models.BooleanField(default=True),
        ),
    ]
