# Generated by Django 4.1.1 on 2024-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0005_role_playable'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='optional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'game')},
        ),
    ]
